name: Backend-ci-cd
on: 
 push:
  branches:
   - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout project
     uses: actions/checkout@v4

   - name: Cache Gradle dependencies
     uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.grradle/wrapper
        key: gradle-${{runner.os}}-${{hasFiles('**/*.gradle*','**/gradle-wrapper.properties')}}
        restore-key: gradle-${{runner.os}}-

   - name: Setup Java
     uses: actions/setup-java@v4
     with:
      java-version: '21'
      distribution: 'temurin'

   - name: Make gradlew executable
     run: chmod +x gradlew

   - name: Run tests
     run: ./gradlew test

   - name: Build project
     run: ./gradlew build

   - name: Upload build artifact
     uses: actions/upload-artifact@v4
     with:
      name: spring-boot-app
      path: build/libs/*.jar


   - name: Login github
     uses: docker/login-action@v3
     with:
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}

   - name: Build Docker Image
     run: docker build -t arzuu1/github-actions-demo .

   - name: Push docker image
     run: docker push arzuu1/github-actions-demo


 deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: Trigger Render deploy
     run: curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
