name: Backend Ci
on:
 push:
 pull_request:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  - name: Setup java
    uses: actions/setup-java@v4
    with:
     java-version: '21'
     distribution: 'temurin'
  - name: Cache gradle dependencies
    uses: actions/cache@v4
    with:
     path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
     key: gradle-${{runner.os}}-${{hashFiles('**/*.gradle*','**/gradle-wrapper.properties')}}
     restore-key: gradle-${{runner.os}}-
  - name: Make gradlew executable
    run: chmod +x gradlew
  - name: Build project
    run: ./gradlew build
     

